### ISSUE TITLE
Readiness/Liveness handlers

### ISSUE THREAD

**Issue by exelban** [hop-city/common#1]
I want to ask if [readiness](https://github.com/hop-city/common/tree/master/readiness) can be transformed into middleware?

The way how it works now makes problems with determining middlewares in right order.

**Comment by marcinbrzeski** [comment]
In readiness/rest.go there is a:
- middleware
- standalone server
- and a method that can attach handlers to existing chi.router

**Comment by exelban** [comment]
thanks, not noticed.
